### ISSUE TITLE
iridium-parser requires --stats

### ISSUE THREAD

**Issue by rpatel3001** [muccc/iridium-toolkit#122]
without --stats, the stats dict is not created. There are unguarded accesses to the stats dict that throw exceptions. either the stats dict creation should be unconditional or all the stats dict accesses should be made conditional on args.do_stats.

**Comment by Sec42** [comment]
Can you provide me with an example commandline where this happens for you? All the normal use-cases work for me.

Reading the code, I realize it can break it with "-o zmq" if not running on a tty -- that's because the zmq mode is intended to be used with stats, but I guess I can silence the output there.

I've pushed a fix on the testing branch. Let me know if that was your problem.

**Comment by rpatel3001** [comment]
It's in a docker container, though I do have tty: true set. Regardless, the testing branch does fix it, thanks.
